import XCTest
@testable import Remo

/// Runs the shared fixture through this platform's timeline algorithm and
/// compares it with the activities the web implementation produced
/// (fixtures/timeline/*.expected.json, regenerated by apps/web golden.test.ts).
final class SharedTimelineFixtureTests: XCTestCase {
    private func fixture(_ name: String) throws -> Data {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("../../../../fixtures/timeline").standardized
        return try Data(contentsOf: root.appendingPathComponent(name))
    }

    private struct Expected: Decodable {
        struct Activity: Decodable {
            let kind: String
            let startedAt: Int64
            let endedAt: Int64
            let latitude: Double?
            let longitude: Double?
            let photoCount: Int
        }
        let activities: [Activity]
    }

    func testMatchesTheActivitiesEveryPlatformExpects() throws {
        let logs = try TimelineImport.decode(data: fixture("remo-timeline-2026-09-01.sample.json"), importedAt: Date(timeIntervalSince1970: 0))
        let expected = try JSONDecoder().decode(Expected.self, from: fixture("remo-timeline-2026-09-01.expected.json")).activities
        let actual = buildTimelineActivities(logs)

        XCTAssertEqual(actual.count, expected.count)
        for (index, (activity, item)) in zip(actual, expected).enumerated() {
            let label = "activity \(index)"
            XCTAssertEqual(activity.kind == .stay ? "stay" : "movement", item.kind, label)
            XCTAssertEqual(Int64((activity.startedAt.timeIntervalSince1970 * 1000).rounded()), item.startedAt, label)
            XCTAssertEqual(Int64((activity.endedAt.timeIntervalSince1970 * 1000).rounded()), item.endedAt, label)
            XCTAssertEqual(activity.photos.count, item.photoCount, label)
            if activity.kind == .stay, let latitude = item.latitude, let longitude = item.longitude {
                XCTAssertEqual(activity.coordinate?.latitude ?? .nan, latitude, accuracy: 1e-5, label)
                XCTAssertEqual(activity.coordinate?.longitude ?? .nan, longitude, accuracy: 1e-5, label)
            }
        }
    }
}
