package com.remo.app

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import java.io.File

/**
 * Runs the shared fixture through this platform's timeline algorithm and
 * compares it with the activities the web implementation produced
 * (the fixture .expected.json file, regenerated by apps/web golden.test.ts).
 */
class SharedTimelineFixtureTest {
    private fun fixture(name: String): File {
        var directory: File? = File("").absoluteFile
        while (directory != null) {
            val candidate = File(directory, "fixtures/timeline/$name")
            if (candidate.isFile) return candidate
            directory = directory.parentFile
        }
        error("fixtures/timeline/$name not found")
    }

    @Test fun matchesTheActivitiesEveryPlatformExpects() = listOf("2026-09-01", "2026-10-01", "2026-10-02").forEach(::assertMatches)

    private fun assertMatches(day: String) {
        val logs = decodeTimelineImport(fixture("remo-timeline-$day.sample.json").readText(), importedAt = 0L)
        val expected = JSONObject(fixture("remo-timeline-$day.expected.json").readText()).getJSONArray("activities")
        val actual = buildTimelineActivities(logs)

        assertEquals(day, expected.length(), actual.size)
        actual.forEachIndexed { index, activity ->
            val item = expected.getJSONObject(index)
            val label = "$day activity $index"
            assertEquals(label, item.getString("kind"), activity.kind.name.lowercase())
            assertEquals(label, item.getLong("startedAt"), activity.startedAt)
            assertEquals(label, item.getLong("endedAt"), activity.endedAt)
            assertEquals(label, item.getInt("photoCount"), activity.photos.size)
            if (activity.kind == TimelineActivityKind.MOVEMENT) assertEquals(label, item.getLong("untrackedMs"), activity.untrackedMs)
            if (activity.kind == TimelineActivityKind.STAY) {
                assertEquals(label, item.getDouble("latitude"), activity.coordinate!!.latitude, 1e-5)
                assertEquals(label, item.getDouble("longitude"), activity.coordinate!!.longitude, 1e-5)
            }
        }
    }
}
